"""Compute the pre-registered statistics S1, S2, S3 and write RESULTS.md."""
import json, os, sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "src"))
from suite import CASES

BYID = {c.id: c for c in CASES}

# The authors' own engine. It is measured by the same suite and shown as a row, but it
# is excluded from every headline statistic; see the conflict-of-interest note.
OURS = {"samyama-graph"}

SYM = {"CONFORMS": "✓", "DIVERGES": "✗", "REJECTS": "!", "INEXPRESSIBLE": "–",
       "NONDETERMINISTIC": "?", "LOAD_FAILED": "∅"}


def main():
    m = json.load(open(os.path.join(HERE, "results", "map.json")))
    mm = json.load(open(os.path.join(HERE, "results", "metamorphic.json")))
    engines = [e["name"] for e in m["engines"]]
    ver = {e["name"]: e["version"] for e in m["engines"]}
    grid = {(c["case"], c["engine"]): c for c in m["cells"]}

    L = []
    L.append("# Results\n")
    L.append("Generated by `src/summarise.py` from `results/map.json` and "
             "`results/metamorphic.json`. Do not edit by hand.\n")

    L.append("## Engines\n")
    L.append("| engine | dialect | version |")
    L.append("|---|---|---|")
    for e in m["engines"]:
        L.append(f"| {e['name']} | {e['dialect']} | {e['version']} |")

    L.append(f"\nEach cell is one exact multiset comparison, repeated "
             f"{m['repeats']} times to confirm the engine is deterministic.\n")

    L.append("## The map\n")
    L.append("| construct | " + " | ".join(engines) + " |")
    L.append("|---" * (len(engines) + 1) + "|")
    for c in CASES:
        cells = [grid[(c.id, e)] for e in engines]
        row = " | ".join(
            SYM[x["verdict"]] + ("\u2020" if x.get("surface") == "vendor-extension" else "")
            for x in cells)
        L.append(f"| `{c.id}` | {row} |")
    L.append("\n\u2713 conforms  \u2717 diverges  ! rejects  \u2013 inexpressible in that dialect  "
             "\u2205 engine failed to load the fixture\n")

    vend = [c for c in m["cells"] if c.get("surface") == "vendor-extension"]
    if vend:
        by_eng = Counter(c["engine"] for c in vend)
        L.append("\u2020 answered through a **vendor extension**: syntax that engine has and "
                 "the common dialect does not. Such a cell says the engine can express "
                 "and compute the construct; it does not say the construct is portable, "
                 "and it is not evidence about the dialect the other engines share. "
                 "Counted here so a vendor cannot raise its score merely by extending "
                 "its own syntax without the reader seeing it.\n")
        L.append("| engine | cells answered via a vendor extension |")
        L.append("|---|---:|")
        for e in engines:
            if by_eng.get(e):
                L.append(f"| {e} | {by_eng[e]} |")
        L.append("")

    acc = {e: Counter() for e in engines}
    for c in m["cells"]:
        acc[c["engine"]][c["verdict"]] += 1
    external = [c for c in m["cells"] if c["engine"] not in OURS]
    tot = Counter(c["verdict"] for c in external)
    ext_engines = [e for e in engines if e not in OURS]

    L.append("## S1 — divergence rate, and S2 — silence ratio\n")
    L.append("S1 is divergences over the cells the engine answered. S2 is divergences "
             "over divergences plus rejections: the share of disagreements the user is "
             "*not* told about.\n")
    L.append("| engine | conforms | diverges | rejects | inexpressible | S1 | S2 |")
    L.append("|---|---:|---:|---:|---:|---:|---:|")
    for e in engines:
        a = acc[e]
        answered = a["CONFORMS"] + a["DIVERGES"]
        den = a["DIVERGES"] + a["REJECTS"]
        s1 = f"{a['DIVERGES']/answered:.2f}" if answered else "n/a"
        s2 = f"{a['DIVERGES']/den:.2f}" if den else "n/a"
        star = " *(ours — excluded from the totals)*" if e in OURS else ""
        L.append(f"| {e}{star} | {a['CONFORMS']} | {a['DIVERGES']} | {a['REJECTS']} | "
                 f"{a['INEXPRESSIBLE']} | {s1} | {s2} |")
    answered = tot["CONFORMS"] + tot["DIVERGES"]
    den = tot["DIVERGES"] + tot["REJECTS"]
    L.append(f"| **all five external engines** | {tot['CONFORMS']} | {tot['DIVERGES']} | "
             f"{tot['REJECTS']} | {tot['INEXPRESSIBLE']} | "
             f"**{tot['DIVERGES']/answered:.2f}** | **{tot['DIVERGES']/den:.2f}** |")

    L.append("\n## Attribution: language difference or implementation defect?\n")
    L.append("A divergence from the ISO reference is only a defect if the engine also "
             "departs from what it documents. The second column re-scores each answer "
             "against the path mode the engine's own manual declares.\n")
    L.append("| construct | engine | vs ISO reference | vs engine's declared mode |")
    L.append("|---|---|---|---|")
    spec = impl = 0
    for c in external:
        if c["verdict"] != "DIVERGES":
            continue
        vd = c.get("verdict_vs_declared")
        if vd == "CONFORMS":
            spec += 1
            tag = "conforms — the deviation is documented"
        elif vd == "DIVERGES":
            impl += 1
            tag = "**diverges — defect**"
        else:
            impl += 1
            tag = "**n/a — the dialect is the standard, so this is a defect**"
        L.append(f"| `{c['case']}` | {c['engine']} | diverges | {tag} |")
    L.append(f"\n**{spec} of {spec+impl} divergences are specified language "
             f"differences** — the engine does exactly what it documents. The "
             f"remaining **{impl}** are departures from the standard the engine "
             f"itself implements.\n")

    L.append("## S3 — answer classes per construct\n")
    L.append("How many distinct answers the engines that accepted the query gave. "
             "One class means the construct is portable.\n")
    L.append("| construct | classes | grouping |")
    L.append("|---|---:|---|")
    for c in CASES:
        classes = defaultdict(list)
        for e in ext_engines:
            cell = grid[(c.id, e)]
            if cell["verdict"] in ("CONFORMS", "DIVERGES"):
                classes[json.dumps(cell.get("observed"), sort_keys=True)].append(e)
        if classes:
            grouping = " / ".join("{" + ", ".join(v) + "}" for v in classes.values())
            L.append(f"| `{c.id}` | {len(classes)} | {grouping} |")

    L.append("\n## Metamorphic self-consistency\n")
    L.append("These need no reference semantics: they hold under WALK, TRAIL, ACYCLIC "
             "and SIMPLE alike, because no restrictor mentions the quantifier bounds. "
             "An engine that breaks one contradicts itself.\n")
    per = Counter(v["engine"] for v in mm["violations"])
    rel = Counter((v["engine"], v["relation"]) for v in mm["violations"])
    L.append("| engine | violations | relations broken |")
    L.append("|---|---:|---|")
    for e in engines:
        rs = sorted({r for (en, r) in rel if en == e})
        L.append(f"| {e} | {per.get(e, 0)} | {', '.join(rs) if rs else '—'} |")
    L.append(f"\nTotal: **{len(mm['violations'])} violations** across "
             f"{len({v['fixture'] for v in mm['violations']})} graphs. "
             f"Minimal reproducers are in `reproducers/`.\n")

    dest = os.path.join(HERE, "RESULTS.md")
    open(dest, "w").write("\n".join(L) + "\n")
    print(f"wrote {dest}")

    # Every number quoted in the paper, as a machine-readable key. The paper's
    # claims registry resolves against this file, so a number cannot drift from the
    # measurement that produced it.
    classes_per_construct = {}
    for c in CASES:
        cl = set()
        for e in ext_engines:
            cell = grid[(c.id, e)]
            if cell["verdict"] in ("CONFORMS", "DIVERGES"):
                cl.add(json.dumps(cell.get("observed"), sort_keys=True))
        if cl:
            classes_per_construct[c.id] = len(cl)
    summary = {
        "n_constructs": len(CASES),
        "n_engines": len(engines),
        "n_engines_external": len(ext_engines),
        "n_cells": len(m["cells"]),
        "n_cells_external": len(external),
        "repeats": m["repeats"],
        "conforms": tot["CONFORMS"],
        "diverges": tot["DIVERGES"],
        "rejects": tot["REJECTS"],
        "inexpressible": tot["INEXPRESSIBLE"],
        "nondeterministic": tot["NONDETERMINISTIC"],
        "s1_divergence_rate": round(tot["DIVERGES"] / answered, 4),
        "s2_silence_ratio": round(tot["DIVERGES"] / den, 4),
        "disagreements": den,
        "divergences_specified": spec,
        "divergences_defect": impl,
        "constructs_multi_class": sum(1 for v in classes_per_construct.values() if v > 1),
        "constructs_single_class": sum(1 for v in classes_per_construct.values() if v == 1),
        "classes_per_construct": classes_per_construct,
        # NC3: cells whose case uses a nondeterministic selector, scored against the
        # admissible set and the per-partition count rather than one chosen path.
        "nondeterministic_selector_cells": sum(
            1 for c in external
            if "ANY" in BYID[c["case"]].ref.selector
            and c["verdict"] in ("CONFORMS", "DIVERGES")),
        "constructs_measured": len(classes_per_construct),
        "metamorphic_violations_total": len(mm["violations"]),
        "metamorphic_violations_external": sum(
            1 for v in mm["violations"] if v["engine"] not in OURS),
        "metamorphic_violations_ours": sum(
            1 for v in mm["violations"] if v["engine"] in OURS),
        "metamorphic_violations_by_engine": {e: per.get(e, 0) for e in engines},
        "metamorphic_clean_engines": [e for e in engines if per.get(e, 0) == 0],
        "engines": {e["name"]: e["version"] for e in m["engines"]},
        "per_engine": {
            e: {
                "conforms": acc[e]["CONFORMS"], "diverges": acc[e]["DIVERGES"],
                "rejects": acc[e]["REJECTS"], "inexpressible": acc[e]["INEXPRESSIBLE"],
                "s1": (round(acc[e]["DIVERGES"] /
                             (acc[e]["CONFORMS"] + acc[e]["DIVERGES"]), 4)
                       if acc[e]["CONFORMS"] + acc[e]["DIVERGES"] else None),
                "s2": (round(acc[e]["DIVERGES"] /
                             (acc[e]["DIVERGES"] + acc[e]["REJECTS"]), 4)
                       if acc[e]["DIVERGES"] + acc[e]["REJECTS"] else None),
            } for e in engines},
    }
    sdest = os.path.join(HERE, "results", "summary.json")
    json.dump(summary, open(sdest, "w"), indent=2)
    print(f"wrote {sdest}")


if __name__ == "__main__":
    main()
