"""Compute the pre-registered statistics S1, S2, S3 and write RESULTS.md."""
import json, os, sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "src"))
from suite import CASES

SYM = {"CONFORMS": "✓", "DIVERGES": "✗", "REJECTS": "!", "INEXPRESSIBLE": "–",
       "NONDETERMINISTIC": "?"}


def main():
    m = json.load(open(os.path.join(HERE, "results", "map.json")))
    mm = json.load(open(os.path.join(HERE, "results", "metamorphic.json")))
    engines = [e["name"] for e in m["engines"]]
    ver = {e["name"]: e["version"] for e in m["engines"]}
    grid = {(c["case"], c["engine"]): c for c in m["cells"]}

    L = []
    L.append("# Results\n")
    L.append("Generated by `src/summarise.py` from `results/map.json` and "
             "`results/metamorphic.json`. Do not edit by hand.\n")

    L.append("## Engines\n")
    L.append("| engine | dialect | version |")
    L.append("|---|---|---|")
    for e in m["engines"]:
        L.append(f"| {e['name']} | {e['dialect']} | {e['version']} |")

    L.append(f"\nEach cell is one exact multiset comparison, repeated "
             f"{m['repeats']} times to confirm the engine is deterministic.\n")

    L.append("## The map\n")
    L.append("| construct | " + " | ".join(engines) + " |")
    L.append("|---" * (len(engines) + 1) + "|")
    for c in CASES:
        row = " | ".join(SYM[grid[(c.id, e)]["verdict"]] for e in engines)
        L.append(f"| `{c.id}` | {row} |")
    L.append("\n✓ conforms  ✗ diverges  ! rejects  – inexpressible in that dialect\n")

    acc = {e: Counter() for e in engines}
    for c in m["cells"]:
        acc[c["engine"]][c["verdict"]] += 1
    tot = Counter(c["verdict"] for c in m["cells"])

    L.append("## S1 — divergence rate, and S2 — silence ratio\n")
    L.append("S1 is divergences over the cells the engine answered. S2 is divergences "
             "over divergences plus rejections: the share of disagreements the user is "
             "*not* told about.\n")
    L.append("| engine | conforms | diverges | rejects | inexpressible | S1 | S2 |")
    L.append("|---|---:|---:|---:|---:|---:|---:|")
    for e in engines:
        a = acc[e]
        answered = a["CONFORMS"] + a["DIVERGES"]
        den = a["DIVERGES"] + a["REJECTS"]
        s1 = f"{a['DIVERGES']/answered:.2f}" if answered else "n/a"
        s2 = f"{a['DIVERGES']/den:.2f}" if den else "n/a"
        L.append(f"| {e} | {a['CONFORMS']} | {a['DIVERGES']} | {a['REJECTS']} | "
                 f"{a['INEXPRESSIBLE']} | {s1} | {s2} |")
    answered = tot["CONFORMS"] + tot["DIVERGES"]
    den = tot["DIVERGES"] + tot["REJECTS"]
    L.append(f"| **all** | {tot['CONFORMS']} | {tot['DIVERGES']} | {tot['REJECTS']} | "
             f"{tot['INEXPRESSIBLE']} | **{tot['DIVERGES']/answered:.2f}** | "
             f"**{tot['DIVERGES']/den:.2f}** |")

    L.append("\n## Attribution: language difference or implementation defect?\n")
    L.append("A divergence from the ISO reference is only a defect if the engine also "
             "departs from what it documents. The second column re-scores each answer "
             "against the path mode the engine's own manual declares.\n")
    L.append("| construct | engine | vs ISO reference | vs engine's declared mode |")
    L.append("|---|---|---|---|")
    spec = impl = 0
    for c in m["cells"]:
        if c["verdict"] != "DIVERGES":
            continue
        vd = c.get("verdict_vs_declared")
        if vd == "CONFORMS":
            spec += 1
            tag = "conforms — the deviation is documented"
        elif vd == "DIVERGES":
            impl += 1
            tag = "**diverges — defect**"
        else:
            impl += 1
            tag = "**n/a — the dialect is the standard, so this is a defect**"
        L.append(f"| `{c['case']}` | {c['engine']} | diverges | {tag} |")
    L.append(f"\n**{spec} of {spec+impl} divergences are specified language "
             f"differences** — the engine does exactly what it documents. The "
             f"remaining **{impl}** are departures from the standard the engine "
             f"itself implements.\n")

    L.append("## S3 — answer classes per construct\n")
    L.append("How many distinct answers the engines that accepted the query gave. "
             "One class means the construct is portable.\n")
    L.append("| construct | classes | grouping |")
    L.append("|---|---:|---|")
    for c in CASES:
        classes = defaultdict(list)
        for e in engines:
            cell = grid[(c.id, e)]
            if cell["verdict"] in ("CONFORMS", "DIVERGES"):
                classes[json.dumps(cell.get("observed"), sort_keys=True)].append(e)
        if classes:
            grouping = " / ".join("{" + ", ".join(v) + "}" for v in classes.values())
            L.append(f"| `{c.id}` | {len(classes)} | {grouping} |")

    L.append("\n## Metamorphic self-consistency\n")
    L.append("These need no reference semantics: they hold under WALK, TRAIL, ACYCLIC "
             "and SIMPLE alike, because no restrictor mentions the quantifier bounds. "
             "An engine that breaks one contradicts itself.\n")
    per = Counter(v["engine"] for v in mm["violations"])
    rel = Counter((v["engine"], v["relation"]) for v in mm["violations"])
    L.append("| engine | violations | relations broken |")
    L.append("|---|---:|---|")
    for e in engines:
        rs = sorted({r for (en, r) in rel if en == e})
        L.append(f"| {e} | {per.get(e, 0)} | {', '.join(rs) if rs else '—'} |")
    L.append(f"\nTotal: **{len(mm['violations'])} violations** across "
             f"{len({v['fixture'] for v in mm['violations']})} graphs. "
             f"Minimal reproducers are in `reproducers/`.\n")

    dest = os.path.join(HERE, "RESULTS.md")
    open(dest, "w").write("\n".join(L) + "\n")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
